version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: nbp
      MONGO_INITDB_ROOT_PASSWORD: nbp
    ports:
      - 27017:27017
    networks:
      - nbpmongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: nbp
      ME_CONFIG_MONGODB_ADMINPASSWORD: nbp
    networks:
      - nbpmongo

networks:
  nbpmongo:
    name: nbpmongo